### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marcos-c1** [marcos-c1/cc-roadmap#1]
## TODO

- Front-End
    - Criar a página principal
        - [x] Barra Lateral  
        - [x] Menu
        - Conteúdo
            - [x] Fazer o mapa mental ou esquematização da trajetória  
   
- Back-End
    - Criar as rotas
        - [x] Home
        - [x] WhoAmI
        - [x] Livros    
    
- Referências Bibliográficas
    - [x] Criar uma lista de livros referentes aos conteúdos apresentados

- [x] Suporte para Linguagem Inglesa

**Comment by marcos-c1** [comment]
O TO-DO serviu explicitamente para ordenar os fatores principais da composição do projeto. O projeto conseguiu atender todos os requisitos necessários para o seu funcionamento.
